# Generated by Django 3.0.3 on 2020-04-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
