# Generated by Django 3.0.3 on 2020-04-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200415_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='album',
            name='total_songs',
            field=models.IntegerField(default=0),
        ),
    ]
