# Generated by Django 3.0.3 on 2020-04-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200416_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
