# Generated by Django 3.0.3 on 2020-04-17 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0004_album_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Is this a private album ? '),
        ),
        migrations.CreateModel(
            name='Shared_album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_album_album_sender', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_album_album_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
